### ISSUE TITLE
Custom cost crash

### ISSUE THREAD

**Issue by laurensversluis** [OpenDigitalWorks/CatchmentAnalyser#2]
When I use custom cost the analysis freezes at 50%. At one point QGIS crashed after a long wait. The cost column in the network layer has a feature with value 0. Could this be the cause of the problem? Are you by any chance dividing by the cost value? I know several network algorithms break if cost is 0, e.g. pgrouting or igraph.

**Comment by jorgegil** [comment]
This is not the case any more. I tested with a custom cost column with 0 (zero) and NULL values and it concluded the analysis.
