### ISSUE TITLE
Message "Polygon tolerance too high for cost band" appears and plugin closes with no output 

### ISSUE THREAD

**Issue by gregmaya** [OpenDigitalWorks/CatchmentAnalyser#9]
log message: 
Catchment Analyser raised an exception: Traceback (most recent call last):
File "C:/Users/g.maya/.qgis2/python/plugins\CatchmentAnalyser-master\catchment_tools.py", line 740, in analysis
self.settings['temp network']
File "C:/Users/g.maya/.qgis2/python/plugins\CatchmentAnalyser-master\catchment_tools.py", line 619, in network_writer
f.setAttribute(name, cost)
TypeError: arguments did not match any overloaded call:
QgsFeature.setAttribute(int, QVariant): argument 1 has unexpected type 'QPyNullVariant'
QgsFeature.setAttribute(QString, QVariant): argument 1 has unexpected type 'QPyNullVariant'

**Comment by jorgegil** [comment]
This occurs in some cases, but the warning is correct. Those polygons cannot be created using the set tolerance value. If the user re-runs with a lower tolerance value it can work.

Also, after some fixes it occurs less frequently and now it creates all polygons except the "impossible" ones.
